spring:
  application:
    name: s-svs
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:svsdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console